USE [master]
GO
/****** Object:  Database [VuelingLastExamDb]    Script Date: 28/03/2019 16:11:09 ******/
CREATE DATABASE [VuelingLastExamDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'VuelingLastExamDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\VuelingLastExamDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'VuelingLastExamDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\VuelingLastExamDb_log.ldf' , SIZE = 204800KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [VuelingLastExamDb] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [VuelingLastExamDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [VuelingLastExamDb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [VuelingLastExamDb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [VuelingLastExamDb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [VuelingLastExamDb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [VuelingLastExamDb] SET ARITHABORT OFF 
GO
ALTER DATABASE [VuelingLastExamDb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [VuelingLastExamDb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [VuelingLastExamDb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [VuelingLastExamDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [VuelingLastExamDb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [VuelingLastExamDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [VuelingLastExamDb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [VuelingLastExamDb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [VuelingLastExamDb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [VuelingLastExamDb] SET  DISABLE_BROKER 
GO
ALTER DATABASE [VuelingLastExamDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [VuelingLastExamDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [VuelingLastExamDb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [VuelingLastExamDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [VuelingLastExamDb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [VuelingLastExamDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [VuelingLastExamDb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [VuelingLastExamDb] SET RECOVERY FULL 
GO
ALTER DATABASE [VuelingLastExamDb] SET  MULTI_USER 
GO
ALTER DATABASE [VuelingLastExamDb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [VuelingLastExamDb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [VuelingLastExamDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [VuelingLastExamDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [VuelingLastExamDb] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'VuelingLastExamDb', N'ON'
GO
ALTER DATABASE [VuelingLastExamDb] SET QUERY_STORE = OFF
GO
