USE [master]
GO
/****** Object:  Database [VuelingExamDb]    Script Date: 3/8/2019 11:45:28 AM ******/
CREATE DATABASE [VuelingExamDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'VuelingExamDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\VuelingExamDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'VuelingExamDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\VuelingExamDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [VuelingExamDb] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [VuelingExamDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [VuelingExamDb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [VuelingExamDb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [VuelingExamDb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [VuelingExamDb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [VuelingExamDb] SET ARITHABORT OFF 
GO
ALTER DATABASE [VuelingExamDb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [VuelingExamDb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [VuelingExamDb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [VuelingExamDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [VuelingExamDb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [VuelingExamDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [VuelingExamDb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [VuelingExamDb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [VuelingExamDb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [VuelingExamDb] SET  DISABLE_BROKER 
GO
ALTER DATABASE [VuelingExamDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [VuelingExamDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [VuelingExamDb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [VuelingExamDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [VuelingExamDb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [VuelingExamDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [VuelingExamDb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [VuelingExamDb] SET RECOVERY FULL 
GO
ALTER DATABASE [VuelingExamDb] SET  MULTI_USER 
GO
ALTER DATABASE [VuelingExamDb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [VuelingExamDb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [VuelingExamDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [VuelingExamDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [VuelingExamDb] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'VuelingExamDb', N'ON'
GO
ALTER DATABASE [VuelingExamDb] SET QUERY_STORE = OFF
GO
USE [VuelingExamDb]
GO